version: '3.8'

services:
  podcast-service:
    build:
      context: .  # Build from the current directory (where Dockerfile is)
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    volumes:
      - episodes:/app/episodes  # Persist the episodes directory
    environment:
      - FLASK_ENV=production  # Optional: Set Flask environment
    restart: unless-stopped  # Restart policy

volumes:
  episodes:  # Named volume for persistent storage
